
-- Esquema y permisos
CREATE SCHEMA IF NOT EXISTS taste_francesinhas;

GRANT USAGE, CREATE ON SCHEMA taste_francesinhas TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA taste_francesinhas
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA taste_francesinhas
    GRANT USAGE, SELECT ON SEQUENCES TO CURRENT_USER;

-- A partir de aqui todo se crea dentro del esquema sin tener que prefijarlo.
SET search_path TO taste_francesinhas, public;

-- ============================================================================
-- Tipos enumerados
-- ============================================================================
CREATE TYPE taste_francesinhas.ROLE_ENUM AS ENUM (
    'USER',
    'ADMIN'
);

CREATE TYPE taste_francesinhas.FRANCESINHA_STATUS_ENUM AS ENUM (
    'PENDING',
    'REJECTED',
    'ACCEPTED'
);

CREATE TYPE taste_francesinhas.FRANCESINHA_TYPE_ENUM AS ENUM (
    'CLASICA',
    'ESPECIAL',
    'VEGANA',
    'KEBAB',
    'MARISCO'
);

-- user va primero porque el resto de tablas la referencian
CREATE TABLE IF NOT EXISTS taste_francesinhas.user (
    id         BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    name       VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role     taste_francesinhas.ROLE_ENUM NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY(id)
);

-- restaurant va antes que francesinha porque francesinha la referencia
CREATE TABLE IF NOT EXISTS taste_francesinhas.restaurant (
    id          BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    proposed_by BIGINT NOT NULL REFERENCES taste_francesinhas.user(id),
    name        VARCHAR(255) NOT NULL,
    address     VARCHAR(255),
    city        VARCHAR(255) NOT NULL,
    phone       VARCHAR(20),
    active      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS taste_francesinhas.francesinha (
    id            BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id BIGINT NOT NULL REFERENCES taste_francesinhas.restaurant(id),
    proposed_by   BIGINT NOT NULL REFERENCES taste_francesinhas.user(id),
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(255),
    price         DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    has_egg       BOOLEAN NOT NULL DEFAULT false,
    has_fries     BOOLEAN NOT NULL DEFAULT false,
    is_spicy      BOOLEAN NOT NULL DEFAULT false,
    type          taste_francesinhas.FRANCESINHA_TYPE_ENUM NOT NULL,
    status        taste_francesinhas.FRANCESINHA_STATUS_ENUM NOT NULL,
    total_reviews BIGINT NOT NULL DEFAULT 0,
    avg_score     DECIMAL(4, 2) NOT NULL DEFAULT 0.00,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS taste_francesinhas.review (
    id                 BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    francesinha_id     BIGINT NOT NULL REFERENCES taste_francesinhas.francesinha(id),
    user_id            BIGINT NOT NULL REFERENCES taste_francesinhas.user(id),
    score_flavor       SMALLINT NOT NULL DEFAULT 0 CHECK(score_flavor BETWEEN 0 AND 5),
    score_sauce        SMALLINT NOT NULL DEFAULT 0 CHECK(score_sauce BETWEEN 0 AND 5),
    score_bread        SMALLINT NOT NULL DEFAULT 0 CHECK(score_bread BETWEEN 0 AND 5),
    score_presentation SMALLINT NOT NULL DEFAULT 0 CHECK(score_presentation BETWEEN 0 AND 5),
    comment            VARCHAR(500) NOT NULL,
    avg_score          NUMERIC(4, 2) NOT NULL DEFAULT 0.00 CHECK(avg_score BETWEEN 0 AND 5),
    created_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS taste_francesinhas.favorite (
    id             BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT NOT NULL REFERENCES taste_francesinhas.user(id),
    francesinha_id BIGINT NOT NULL REFERENCES taste_francesinhas.francesinha(id),
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY(id),
    UNIQUE(user_id, francesinha_id)
);



-- INSERTS


-- ADMIN USER
INSERT INTO taste_francesinhas.user (email, password, role, created_at) VALUES
  ('admin@francwinhas.com', '$2a$12$16mBhB8Xci3Vxu.jmP/Ej.W0xn3fRdTuGIlN4RWQurG7RWaHhZjqO', 'ADMIN', NOW());

INSERT INTO taste_francesinhas.restaurant (proposed_by, name, address, city, active, created_at) VALUES
  (1, 'Café Rio de Janeiro', 'Rua do Cavalhido 22, 4250-204', 'Oporto', TRUE, NOW()),
  (1, 'O Recomeço', 'Rua Central da Gandra 1299, 4585-116', 'Paredes', TRUE, NOW()),
  (1, 'Leana Kebab', 'Rua Luis Barroso 514, 4760-111', 'Vilanova de Famalicão', TRUE, NOW()),
  (1, 'Leana Kebab Póvoa', 'Avenida de Baixo 8, 4490-409', 'Póvoa de Varzim', TRUE, NOW()),
  (1, 'Leana Kebab Guimarães', 'Avenida Dom Afonso Henriques 16, 4810-225', 'Guimarães', TRUE, NOW()),
  (1, 'Time Out Sports Bar', 'Avenida Eng. Armando Magalhães 371, 4440-505', 'Valongo', TRUE, NOW()),
  (1, 'Ritual das Francesinhas', 'Rua 33, nº140, 4500-807', 'Espinho', TRUE, NOW()),
  (1, 'Ponit', 'Rua Manuel Pereira da Silva 216, 4200-894', 'Oporto', TRUE, NOW()),
  (1, 'Os Eusébios', 'Avenida Dr. Carlos Pinto Ferreira 2028, 4480-665', 'Vila do Conde', TRUE, NOW()),
  (1, 'Bufete Fase', 'Rua de Santa Catarina 1147, 4000-457', 'Oporto', TRUE, NOW()),
  (1, 'Perto do Cais', 'Rua do Rei Ramiro 786, 4400-281', 'Vila Nova de Gaia', TRUE, NOW()),
  (1, 'Taberna Belga', 'Rua Mario de Almeida 67, 4700-395', 'Braga', TRUE, NOW()),
  (1, 'Cerqueira''s Lounge & Restaurant', 'Praça da Liberdade loja A8, 4900-326', 'Viana do Castelo', TRUE, NOW()),
  (1, 'Cerqueira''s in Rio', 'Rua de Limia, 4900', 'Viana do Castelo', TRUE, NOW()),
  (1, 'Restaurante Nuevo Pendiente', 'Rua das Propostas 99', 'Braga', FALSE, NOW());


INSERT INTO taste_francesinhas.francesinha  (restaurant_id, proposed_by, name, price, has_egg, has_fries, is_spicy, type, status, total_reviews, avg_score, created_at)
VALUES
  (1, 1, 'Francesinha normal', 6.20, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (1, 1, 'Francesinha com Ovo', 6.50, true, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (1, 1, 'Francesinha com batata', 7.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (1, 1, 'Francesinha com ovo e batata', 7.60, true, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (1, 1, 'Francesinha vegetariana', 7.60, false, true, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (1, 1, 'Mini Francesinha', 5.20, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (1, 1, 'Mini Francesinha con batata', 6.60, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (2, 1, 'Francesinha a recomeço', 14.00, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (2, 1, 'Francesinha com Ovo', 12.00, true, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (2, 1, 'Francesinha simples', 10.50, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (2, 1, 'Francesinha com batata', 12.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (3, 1, 'Francesinha Kebab', 13.95, false, true, false, 'KEBAB', 'ACCEPTED', 0, 0.00, NOW()),
  (3, 1, 'Francesinha de Vitela', 13.95, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (3, 1, 'Francesinha de Frango', 13.95, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (3, 1, 'Francesinha de Falafel', 13.95, false, true, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (4, 1, 'Francesinha Kebab', 13.95, false, true, false, 'KEBAB', 'ACCEPTED', 0, 0.00, NOW()),
  (4, 1, 'Francesinha de Vitela', 13.95, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (4, 1, 'Francesinha de Frango', 13.95, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (4, 1, 'Francesinha de Falafel', 13.95, false, true, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (5, 1, 'Francesinha Kebab', 13.95, false, true, false, 'KEBAB', 'ACCEPTED', 0, 0.00, NOW()),
  (5, 1, 'Francesinha de Vitela', 13.95, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (5, 1, 'Francesinha de Frango', 13.95, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (5, 1, 'Francesinha de Falafel', 13.95, false, true, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (6, 1, 'Alemazinha Original', 10.95, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (6, 1, 'Alemazinha Beckenbauer', 14.95, false, false, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (6, 1, 'Alemazinha Istambil-Kebab', 13.95, false, false, false, 'KEBAB', 'ACCEPTED', 0, 0.00, NOW()),
  (7, 1, 'Bife lomo de boi', 14.00, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (7, 1, 'Bife de novilho', 11.00, false, false, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (7, 1, 'Bife de Porco', 9.00, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (7, 1, 'Sem bife', 5.00, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (8, 1, 'Tradicional', 11.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (8, 1, 'Poveira', 4.50, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha normal', 3.60, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha normal a Eusébios', 5.20, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha normal à caxineiro', 4.20, false, false, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha normal à caxineiro no prato', 5.80, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha normal na caçarola', 6.80, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha especial', 7.50, false, false, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha especial aos Eusébios', 8.50, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha da casa', 10.00, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (9, 1, 'Francesinha à bairrada', 10.00, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (10, 1, 'Francesinha à fase', 12.50, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (10, 1, 'Francesinha vegetariana', 5.50, false, false, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (11, 1, 'Francesinha com ovo e batata', 13.00, true, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (11, 1, 'Francesinha com ovo ou batata', 12.50, true, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (11, 1, 'Francesinha vegetariana', 14.50, false, true, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (12, 1, 'Francesinha', 12.90, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (12, 1, 'Francesinha tradicional', 11.95, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (12, 1, 'Francesinha de hamburguer', 11.90, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (12, 1, 'Francesinha de legumes', 11.90, false, true, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (12, 1, 'Francesinha de lomo de boi', 16.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (12, 1, 'Francesinha de perú/frango', 13.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha Cerqueira''s', 9.00, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha atabernada', 9.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha de lomo', 14.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha Cerqueira''s XL', 14.00, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha vegetariana', 9.00, false, true, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha de alheira', 9.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha de alheira vegetariana', 9.00, false, true, false, 'VEGANA', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha de marisco', 9.50, false, true, false, 'MARISCO', 'ACCEPTED', 0, 0.00, NOW()),
  (13, 1, 'Francesinha light', 9.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (14, 1, 'Francesinha Cerqueira''s in Rio', 14.00, false, true, false, 'ESPECIAL', 'ACCEPTED', 0, 0.00, NOW()),
  (14, 1, 'Francesinha de frango', 13.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (14, 1, 'Francesinha de alheira', 14.00, false, true, false, 'CLASICA', 'ACCEPTED', 0, 0.00, NOW()),
  (1, 1, 'Francesinha pendiente de prueba 1', 8.50, false, false, false, 'CLASICA', 'PENDING', 0, 0.00, NOW()),
  (7, 1, 'Francesinha pendiente de prueba 2', 12.00, true, true, true, 'ESPECIAL', 'PENDING', 0, 0.00, NOW()),
  (15, 1, 'Francesinha pendiente de prueba 3', 10.00, false, true, false, 'VEGANA', 'PENDING', 0, 0.00, NOW());