spring:
  application:
    name: taste_francesinhas_backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      # validate: verifica que las entidades coincidan con las tablas (no las modifica)
      # Usa 'create-drop' solo en dev si quieres que Hibernate cree las tablas
      ddl-auto: validate
    show-sql: ${DB_SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate:
        default_schema: taste_francesinhas
        dialect: org.hibernate.dialect.PostgreSQLDialect

  threads:
    virtual:
      enabled: true

server:
  port: ${PORT:8082}
  servlet:
    context-path: /tastefrancesinhas

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  info:
    env:
      enabled: true

info:
  app:
    name: Taste Francesinhas
    description: API REST para descubrir, proponer y valorar francesinhas
    version: 0.0.1

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 #1 hora
    refresh-expiration: 604800000 #7 dias

