spring:
  application:
    name: taste_francesinhas_backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      # validate: verifica que las entidades coincidan con las tablas (no las modifica)
      # Usa 'create-drop' solo en dev si quieres que Hibernate cree las tablas
      ddl-auto: validate
    show-sql: ${DB_SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate:
        default_schema: taste_francesinhas
        dialect: org.hibernate.dialect.PostgreSQLDialect

  threads:
    virtual:
      enabled: true

  # Spring por defecto limita multipart a 1MB. Subimos a 5MB que es el limite tambien validado en el frontend.
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: ${PORT:8080}
  servlet:
    context-path: /tastefrancesinhas

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  info:
    env:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

info:
  app:
    name: Taste Francesinhas
    description: API REST para descubrir, proponer y valorar francesinhas
    version: 0.0.1

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 900000 #1 hora
    refresh-expiration: 3600000 #604800000 #7 dias

supabase:
  url: ${SUPABASE_URL}
  bucket: ${SUPABASE_BUCKET}
  s3:
    endpoint: ${SUPABASE_S3_ENDPOINT}
    region: ${SUPABASE_S3_REGION}
    access-key: ${SUPABASE_S3_ACCESS_KEY}
    secret-key: ${SUPABASE_S3_SECRET_KEY}

